# Generated by Django 3.1.4 on 2023-01-26 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IngotForum', '0002_auto_20230106_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ingnote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
