# Generated by Django 3.1.4 on 2023-02-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngotForum', '0003_ingnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingnote',
            name='title',
            field=models.TextField(default='Untitled', max_length=100),
        ),
    ]
