# Generated by Django 4.1.7 on 2023-03-17 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_journal_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('number_in_stock', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(choices=[('FIC', 'Fiction'), ('SFI', 'Sci Fi'), ('FAN', 'Fantasy'), ('MAN', 'Manga'), ('OTH', 'Other'), ('HOR', 'Horror'), ('COM', 'Comedy'), ('DRA', 'Drama')], max_length=3)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author')),
            ],
        ),
    ]
